<a href="https://colab.research.google.com/github/prem413o/AI-ML-Complete/blob/main/Panda_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/DATA SET/raw_data.csv")
df
df["income"]

#data transfoming
df2=df.copy()
df2["tax"]=df2["income"].apply(lambda x: "20%" if x>=50000 else "10%")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [ ]:
#use of map
gender_map={"Male": "M","Female":"F","Unknown":"U"}
df2["gender"]=df2["gender"].map(gender_map)

In [ ]:
df2
df2=df2.assign(new_income=df2["income"] *1.1)

In [ ]:
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%     63800.0

In [ ]:
#renmaing
df2.columns=["Id","Name","Age","Country","Gender","Income","Tax","New_Income"]
df2

    Id          Name   Age Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%     63800.0

In [ ]:
#renaming particular column
df2=df2.rename(columns={"Income":"Salary"})
df2

    Id          Name   Age Country Gender   Salary  Tax  New_Income
0    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%     63800.0

In [ ]:
df2.sort_values("Salary")
sorted_value=df2.sort_values("Salary",ascending=False)
sorted_value
sorted_value.reset_index()

#ranking
sorted_value["Ranking"]=sorted_value["Salary"].rank(ascending=False)
sorted_value

    Id          Name   Age Country Gender   Salary  Tax  New_Income  Ranking
6    6           NaN  45.0   India      F  73000.0  20%     80300.0      1.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0      2.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0      3.5
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0      3.5
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%     63800.0      5.0
0    1      John Doe  29.0     USA      M  55000.0  20%     60500.0      6.5
1    1      John Doe  29.0     USA      M  55000.0  20%     60500.0      6.5
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0      8.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0      9.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0     10.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN      NaN

In [ ]:
df
df[["name","age","country","gender","income","id"]]

NameError: name 'df' is not defined